name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install

      - run: yarn lint
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install

      - run: yarn build
      - run: yarn size-limit

  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@eqworks'
          always-auth: true

      - run: npx depcheck

  release:
    name: Trigger a release
    runs-on: ubuntu-latest
    needs: [lint, build, depcheck]
    if: contains(github.event_name, 'push')
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Create auto-tag
        if: ${{ success() }}
        run: npx @eqworks/release tag --github -v
        env:
          GITHUB_OWNER: EQWorks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
