name: Node.js Package - alpha tag

on:
  push:
    tags:
      - 'v*-alpha*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
          scope: '@eqworks'
      - run: yarn publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_NPM_TOKEN_PUBLISH }}

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: '@eqworks'
          always-auth: true
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.CD_NPM_TOKEN_PUBLISH }}" > .npmrc
      - run: yarn publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_NPM_TOKEN_PUBLISH }}
