name: Node.js Package

on:
  push:
    tags:
      - 'v*' # proceeds eg: v1.0
      - '!v*-*' # skips eg: v1.2.99-beta1, v3.5.0-test, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@eqworks'
          always-auth: true
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@eqworks'
          always-auth: true
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_NPM_TOKEN_PUBLISH }}
