name: Storybook Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install

      - name: Deploy
        run: yarn storybook-to-ghpages --ci
        env:
          GH_TOKEN: EQWorks:${{ secrets.GITHUB_TOKEN }}
